fragment PageParts on Page {
  blocks {
    __typename
    ... on PageBlocksHero {
      heading
      subheading
      description
      image
    }
    ... on PageBlocksFeatures {
      items {
        __typename
        article {
          ... on Document {
            id
          }
        }
      }
    }
    ... on PageBlocksContent {
      items {
        __typename
        image
        name
        description
        href
      }
    }
    ... on PageBlocksVideo {
      items {
        __typename
        title
        description
        url
      }
    }
  }
}

fragment CategoryParts on Category {
  title
  related {
    __typename
    category {
      ... on Document {
        id
      }
    }
  }
  description
}

fragment AuthorParts on Author {
  title
  email
  name
  twitter
  github
  linkedin
  bio
  image
}

fragment PostParts on Post {
  title
  date
  image
  authors {
    __typename
    author {
      ... on Document {
        id
      }
    }
  }
  categories {
    __typename
    category {
      ... on Document {
        id
      }
    }
  }
  description
  body
}
